version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    env_file: .env
    restart: always
  db:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
    restart: always